services:

  backend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    networks:
      - intyrasense-network

  frontend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
    env_file:
      - ../.env
    depends_on:
      - backend
    networks:
      - intyrasense-network

networks:
  intyrasense-network:
    driver: bridge